"""add missing fields in Artist model

Revision ID: 1ec7887b9aed
Revises: 57d2475bd92d
Create Date: 2020-05-21 07:50:05.375066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec7887b9aed'
down_revision = '57d2475bd92d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=256), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('website', sa.String(length=2048), nullable=True))
    op.drop_column('Artist', 'genres')
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('Artist', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('Artist', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'image_link',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('Artist', 'facebook_link',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.drop_column('Artist', 'genres')
    op.add_column('Artist', sa.Column('genres', sa.String(length=120), nullable=True))
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
