"""empty message

Revision ID: 57d2475bd92d
Revises: 03afcb7d03c8
Create Date: 2020-05-21 07:45:00.295113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d2475bd92d'
down_revision = '03afcb7d03c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('Venue', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'image_link',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('Venue', 'facebook_link',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
